---
- name: Install Zenoh from deb
  hosts: all

  tasks:
    - name: Install Zenoh prerequisites
      become: true
      shell: |
        sudo apt update
        sudo apt install wget unzip -y

    - name: Install Zenoh on x86_64
      become: true
      shell: |
        wget -O ~/zenoh-pkgs.zip https://github.com/eclipse-zenoh/zenoh/releases/download/{{ zenoh | quote }}/zenoh-{{ zenoh | quote }}-x86_64-unknown-linux-gnu-debian.zip
        unzip ~/zenoh-pkgs.zip -d ~/
        sudo dpkg -i ~/zenoh*.deb
        rm -f ~/zenoh-pkgs.zip ~/zenoh*.deb
      when: ansible_architecture == "x86_64"

    - name: Install Zenoh on arm64
      become: true
      shell: |
        wget -O ~/zenoh-pkgs.zip https://github.com/eclipse-zenoh/zenoh/releases/download/{{ zenoh | quote }}/zenoh-{{ zenoh | quote }}-aarch64-unknown-linux-gnu-debian.zip
        unzip ~/zenoh-pkgs.zip -d ~/
        sudo dpkg -i ~/zenoh*.deb
        rm -f ~/zenoh-pkgs.zip ~/zenoh*.deb
      when: ansible_architecture == "arm64"

    - name: Install zenoh-python and opencv env for zcam
      become: true
      shell: |
        sudo apt update
        sudo apt install python3-pip libpopencv-dev -y
        pip install -U pip
        pip install --no-cache-dir eclipse-zenoh=={{ zenoh | quote }} opencv-python numpy imutils
